niopendisks/niclosedisks: Cleanup boot message
Cleanup stdout prints to match other init.d scripts. I.e. only print
script name instead of $0, which can be the filepath.

Signed-off-by: Haris Okanovic <haris.okanovic@ni.com>
Natinst-Rally-ID: F12416
Natinst-ReviewBoard-ID: 204904

diff --git a/recipes-ni/initscripts-nilrt/files/niclosedisks b/recipes-ni/initscripts-nilrt/files/niclosedisks
--- a/recipes-ni/initscripts-nilrt/files/niclosedisks
+++ b/recipes-ni/initscripts-nilrt/files/niclosedisks
@@ -3,11 +3,13 @@ set -e
 set -u
 set -o pipefail
 
+SCRIPT_NAME="niclosedisks"
+
 # begin output
-echo -n "$0: "
+echo -n "$SCRIPT_NAME: "
 
 function error () {
-    echo >&2 "$0: ERROR: $*"
+    echo >&2 "$SCRIPT_NAME: ERROR: $*"
     exit 1
 }
 
