test-niopendisks-init/test-niclosedisks-init: Fixup PASS/FAIL print
Add colon (:) after PASS and FAIL.

Signed-off-by: Haris Okanovic <haris.okanovic@ni.com>
Natinst-ReviewBoard-ID: 214039

diff --git a/recipes-ni/initscripts-nilrt/files/test-niclosedisks-init b/recipes-ni/initscripts-nilrt/files/test-niclosedisks-init
--- a/recipes-ni/initscripts-nilrt/files/test-niclosedisks-init
+++ b/recipes-ni/initscripts-nilrt/files/test-niclosedisks-init
@@ -3,7 +3,7 @@ set -e
 set -u
 set -o pipefail
 
-trap 'exitCode="$?"; set +e; echo "FAIL $0"; exit "$exitCode"' EXIT
+trap 'exitCode="$?"; set +e; echo "FAIL: $0"; exit "$exitCode"' EXIT
 
 echo "check that niclosedisks runs right before reboot"
 ls -l "/etc/rc6.d/S40umountfs"
@@ -15,5 +15,5 @@ ls -l "/etc/rc0.d/S40umountfs"
 ls -l "/etc/rc0.d/S41niclosedisks"
 echo "OK"
 
-echo "PASS $0"
+echo "PASS: $0"
 trap - EXIT
diff --git a/recipes-ni/initscripts-nilrt/files/test-niopendisks-init b/recipes-ni/initscripts-nilrt/files/test-niopendisks-init
--- a/recipes-ni/initscripts-nilrt/files/test-niopendisks-init
+++ b/recipes-ni/initscripts-nilrt/files/test-niopendisks-init
@@ -3,7 +3,7 @@ set -e
 set -u
 set -o pipefail
 
-trap 'exitCode="$?"; set +e; echo "FAIL $0"; exit "$exitCode"' EXIT
+trap 'exitCode="$?"; set +e; echo "FAIL: $0"; exit "$exitCode"' EXIT
 
 echo "check that niopendisks runs before mountall and sysfs"
 ls -l "/etc/rcS.d/S00niopendisks"
@@ -11,5 +11,5 @@ ls -l "/etc/rcS.d/S02mountall.sh"
 ls -l "/etc/rcS.d/S02sysfs.sh"
 echo "OK"
 
-echo "PASS $0"
+echo "PASS: $0"
 trap - EXIT
