opkg: integrate custom ptests with existing opkg-ptest harness
Opkg now includes a -ptest pkg that installs the builtin ats. Modify
run-ptest override to make sure the builtin ats is also run.

Signed-off-by: Alejandro del Castillo <alejandro.delcastillo@ni.com>
Acked-by: Alex Stewart <alex.stewart@ni.com>
Natinst-ReviewBoard-ID: 286918

diff --git a/recipes-devtools/opkg/files/run-ptest b/recipes-devtools/opkg/files/run-ptest
--- a/recipes-devtools/opkg/files/run-ptest
+++ b/recipes-devtools/opkg/files/run-ptest
@@ -1,6 +1,15 @@
 #! /bin/sh
 
-for test in $(find ./ -name "test*"); do
+OPKG_PATH=$(which opkg)
+
+make OPKG_PATH=$OPKG_PATH run-tests
+if [ $? -ne 0 ]; then
+	echo "FAIL: opkg-ats"
+else
+	echo "PASS: opkg-ats"
+fi
+
+for test in $(find -type f -maxdepth 1 -name "test*"); do
 	./$test
 	if [ $? -ne 0 ]; then
 		echo "FAIL: $test"
