initrdscripts: fixup whitespace
Use tabs for indentation in bash scripts.

This commit is not intended to change functionality.

Signed-off-by: Alex Stewart <alex.stewart@ni.com>

diff --git a/recipes-core/initrdscripts/files/disk_config_x64 b/recipes-core/initrdscripts/files/disk_config_x64
--- a/recipes-core/initrdscripts/files/disk_config_x64
+++ b/recipes-core/initrdscripts/files/disk_config_x64
@@ -2,87 +2,87 @@
 
 install_default_error_handler()
 {
-    trap 'handle_err ${BASH_SOURCE} ${LINENO} ${FUNCNAME:-unknown} $? "$BASH_COMMAND"' ERR
+	trap 'handle_err ${BASH_SOURCE} ${LINENO} ${FUNCNAME:-unknown} $? "$BASH_COMMAND"' ERR
 }
 
 handle_err()
 {
-    TMP_EVAL=`eval echo $5`
-    die "$1:$2 (fn=$3): Unexpected status code $4 while running command: '$TMP_EVAL'"
+	TMP_EVAL=`eval echo $5`
+	die "$1:$2 (fn=$3): Unexpected status code $4 while running command: '$TMP_EVAL'"
 }
 
 disk_partition()
 {
-    local disk="$1"
+	local disk="$1"
 
-    umount "$disk"? || true
+	umount "$disk"? || true
 
-    dd if="/dev/zero" of="$disk" bs=1M count=1
+	dd if="/dev/zero" of="$disk" bs=1M count=1
 
-    parted -s "$disk" --align optimal      \
-        mklabel "gpt"                      \
-        mkpart "niboota"       1MB  250MB  \
-        mkpart "nibootb"     250MB  500MB  \
-        mkpart "niuser"      500MB  100%
+	parted -s "$disk" --align optimal \
+		mklabel "gpt" \
+		mkpart "niboota"   1MB  250MB \
+		mkpart "nibootb" 250MB  500MB \
+		mkpart "niuser"  500MB  100%
 
-    # Per https://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/
-    #  C12A7328-F81F-11D2-BA4B-00A0C93EC93B -- EFI System Partition
-    #  4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709 -- Root Partition (x86-64)
-    sgdisk --typecode="1:C12A7328-F81F-11D2-BA4B-00A0C93EC93B" "$disk"
-    sgdisk --typecode="2:C12A7328-F81F-11D2-BA4B-00A0C93EC93B" "$disk"
-    sgdisk --typecode="3:4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709" "$disk"
+	# Per https://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/
+	#  C12A7328-F81F-11D2-BA4B-00A0C93EC93B -- EFI System Partition
+	#  4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709 -- Root Partition (x86-64)
+	sgdisk --typecode="1:C12A7328-F81F-11D2-BA4B-00A0C93EC93B" "$disk"
+	sgdisk --typecode="2:C12A7328-F81F-11D2-BA4B-00A0C93EC93B" "$disk"
+	sgdisk --typecode="3:4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709" "$disk"
 
-    partprobe -s "$disk"
+	partprobe -s "$disk"
 }
 
 partition_format()
 {
-    local disk="$1" label="$2"
+	local disk="$1" label="$2"
 
-    partitions=($(lsblk -rnpo NAME -x NAME ${disk} | tail +2))
-    disk_check "$disk"
+	partitions=($(lsblk -rnpo NAME -x NAME ${disk} | tail +2))
+	disk_check "$disk"
 
-    case "$label" in
-        niboota)
-            dd if="/dev/zero" of="${partitions[0]}" bs=1M count=1
-            mkfs.vfat -n "niboota" "${partitions[0]}"
-            ;;
-        nibootb)
-            dd if="/dev/zero" of="${partitions[1]}" bs=1M count=1
-            mkfs.vfat -n "nibootb" "${partitions[1]}"
-            ;;
-        niuser)
-            # niuser partition is managed by initramfs
-            dd if="/dev/zero" of="${partitions[2]}" bs=1M count=1
-            ;;
-        *)
-            die "Invalid or unspecified label!"
-    esac
+	case "$label" in
+		niboota)
+			dd if="/dev/zero" of="${partitions[0]}" bs=1M count=1
+			mkfs.vfat -n "niboota" "${partitions[0]}"
+			;;
+		nibootb)
+			dd if="/dev/zero" of="${partitions[1]}" bs=1M count=1
+			mkfs.vfat -n "nibootb" "${partitions[1]}"
+			;;
+		niuser)
+			# niuser partition is managed by initramfs
+			dd if="/dev/zero" of="${partitions[2]}" bs=1M count=1
+			;;
+		*)
+			die "Invalid or unspecified label!"
+	esac
 }
 
 partition_check()
 {
-    local partition="$1"
+	local partition="$1"
 
-    [[ -e "$partition" ]] || die "Invalid or unspecified partition!"
+	[[ -e "$partition" ]] || die "Invalid or unspecified partition!"
 }
 
 disk_check()
 {
-    local disk="$1"
+	local disk="$1"
 
-    [[ -b "$disk" ]] || die "Invalid or unspecified disk!"
+	[[ -b "$disk" ]] || die "Invalid or unspecified disk!"
 }
 
 disk_setup()
 {
-    local disk="$1"
+	local disk="$1"
 
-    disk_check "$disk"
+	disk_check "$disk"
 
-    disk_partition "$disk"
+	disk_partition "$disk"
 
-    partition_format "$disk" "niboota"
-    partition_format "$disk" "nibootb"
-    partition_format "$disk" "niuser"
+	partition_format "$disk" "niboota"
+	partition_format "$disk" "nibootb"
+	partition_format "$disk" "niuser"
 }
diff --git a/recipes-core/initrdscripts/files/ni_provisioning b/recipes-core/initrdscripts/files/ni_provisioning
--- a/recipes-core/initrdscripts/files/ni_provisioning
+++ b/recipes-core/initrdscripts/files/ni_provisioning
@@ -4,19 +4,19 @@ INVALID_NILRT_ID_MSG="Invalid value for PROVISION_PART_NILRT_ID. Use UUID=<value
 
 # verify required tools are installed
 for toolName in poweroff reboot mount umount sync ls rm ln mkdir cp echo printf dirname basename find grep egrep tar bzip2 bunzip2 lsblk cut udevadm date sleep head; do
-    if ! type "$toolName" >/dev/null; then
-        printf "\n***Error: Missing $toolName\n"
-        printf "PROVISIONING FAILED!"
-        exit 1
-    fi
+	if ! type "$toolName" >/dev/null; then
+		printf "\n***Error: Missing $toolName\n"
+		printf "PROVISIONING FAILED!"
+		exit 1
+	fi
 done
 
 if [ -e /ni_provisioning.common ]; then
-    source /ni_provisioning.common
+	source /ni_provisioning.common
 else
-    printf "\n***Error: File ni_provisioning.common not found!\n"
-    printf "PROVISIONING FAILED!"
-    exit 1
+	printf "\n***Error: File ni_provisioning.common not found!\n"
+	printf "PROVISIONING FAILED!"
+	exit 1
 fi
 
 early_setup "$@"
@@ -25,93 +25,93 @@ early_setup "$@"
 source_default_answer_file
 
 if in_recovery_mode; then
-    echo "Automatic provision and reboot in recovery mode"
-    PROVISION_REPARTITION_TARGET="y"
-    PROVISION_REBOOT_METHOD="reboot"
+	echo "Automatic provision and reboot in recovery mode"
+	PROVISION_REPARTITION_TARGET="y"
+	PROVISION_REBOOT_METHOD="reboot"
 fi
 
 if [[ $restore == "provision-safe" ]]; then
-    # source user's answer file, if present
-    source_answer_file
-    echo
+	# source user's answer file, if present
+	source_answer_file
+	echo
 
-    if [[ "$PROVISION_REPARTITION_TARGET" != "y" ]]; then
-        ask_for_continue
-    fi
+	if [[ "$PROVISION_REPARTITION_TARGET" != "y" ]]; then
+		ask_for_continue
+	fi
 
-    if [[ $PROVISION_REPARTITION_TARGET == "y" ]]; then
-        source /ni_provisioning.safemode
-        if [[ "${FORCE_PROVISIONING}" -eq 1 ]]; then
-            PROVISION_REBOOT_METHOD=${RESTART_OPTION}
-        fi
-        ASK_BEFORE_REBOOT=1
-    fi
+	if [[ $PROVISION_REPARTITION_TARGET == "y" ]]; then
+		source /ni_provisioning.safemode
+		if [[ "${FORCE_PROVISIONING}" -eq 1 ]]; then
+			PROVISION_REBOOT_METHOD=${RESTART_OPTION}
+		fi
+		ASK_BEFORE_REBOOT=1
+	fi
 elif [[ $restore == "backward-migrate" ]]; then
-    source /ni_provisioning.safemode
-    ASK_BEFORE_REBOOT=1
-    PROVISION_REBOOT_METHOD="reboot"
+	source /ni_provisioning.safemode
+	ASK_BEFORE_REBOOT=1
+	PROVISION_REBOOT_METHOD="reboot"
 elif [[ $restore == "provision" ]]; then
-    # source user's answer file, if present
-    source_answer_file
-    echo
+	# source user's answer file, if present
+	source_answer_file
+	echo
 
-    if [[ "$PROVISION_PART_NILRT_ID" = "auto" ]]; then
-        ask_for_continue
+	if [[ "$PROVISION_PART_NILRT_ID" = "auto" ]]; then
+		ask_for_continue
 
-        if [[ $PROVISION_REPARTITION_TARGET == "y" ]]; then
-            provision_target usb
-        fi
-    else
-        # TODO
-        die "Not supported yet"
+		if [[ $PROVISION_REPARTITION_TARGET == "y" ]]; then
+			provision_target usb
+		fi
+	else
+		# TODO
+		die "Not supported yet"
 
-        case "$PROVISION_PART_NILRT_ID" in
-            LABEL=*)
-                ;;
-            UUID=*)
-                ;;
-            PARTUUID=*)
-                ;;
-            *)
-                die "$INVALID_NILRT_ID_MSG"
-                ;;
-        esac
+		case "$PROVISION_PART_NILRT_ID" in
+			LABEL=*)
+				;;
+			UUID=*)
+				;;
+			PARTUUID=*)
+				;;
+			*)
+				die "$INVALID_NILRT_ID_MSG"
+				;;
+		esac
 
-        column=${PROVISION_PART_NILRT_ID%%=*}
-        nilrt_id=${PROVISION_PART_NILRT_ID##*=}
-        if [[ -z "$nilrt_id" ]]; then
-            die "$INVALID_NILRT_ID_MSG"
-        fi
-        if [[ "$column" = "LABEL" ]]; then
-            grep_options=""
-        else
-            grep_options="-i"
-        fi
-        nilrt_path=`lsblk -rnpo NAME,"$column" | grep $grep_options "$nilrt_id" | cut -d' ' -f1`
-        if [[ -z "$nilrt_path" ]]; then
-            die "Partition with "$PROVISION_PART_NILRT_ID" not found."
-        fi
+		column=${PROVISION_PART_NILRT_ID%%=*}
+		nilrt_id=${PROVISION_PART_NILRT_ID##*=}
+		if [[ -z "$nilrt_id" ]]; then
+			die "$INVALID_NILRT_ID_MSG"
+		fi
+		if [[ "$column" = "LABEL" ]]; then
+			grep_options=""
+		else
+			grep_options="-i"
+		fi
+		nilrt_path=`lsblk -rnpo NAME,"$column" | grep $grep_options "$nilrt_id" | cut -d' ' -f1`
+		if [[ -z "$nilrt_path" ]]; then
+			die "Partition with "$PROVISION_PART_NILRT_ID" not found."
+		fi
 
-        ask_for_continue
-        if [[ $PROVISION_REPARTITION_TARGET == "y" ]]; then
-            if [[ "$column" = "UUID" ]]; then
-                uuid="$nilrt_id"
-            else
-                uuid=""
-            fi
-            restore_runmode_image "$nilrt_path" "$uuid" "$PROVISION_PART_NILRT_LABEL"
-        fi
-    fi
+		ask_for_continue
+		if [[ $PROVISION_REPARTITION_TARGET == "y" ]]; then
+			if [[ "$column" = "UUID" ]]; then
+				uuid="$nilrt_id"
+			else
+				uuid=""
+			fi
+			restore_runmode_image "$nilrt_path" "$uuid" "$PROVISION_PART_NILRT_LABEL"
+		fi
+	fi
 
 elif [[ $restore == "migrate" ]]; then
-    PROVISION_REBOOT_METHOD="reboot"
-    provision_target onboard
+	PROVISION_REBOOT_METHOD="reboot"
+	provision_target onboard
 else
-    die "Invalid restore mode."
+	die "Invalid restore mode."
 fi
 
 if [[ "$ASK_BEFORE_REBOOT" -ne 0 ]] && [[ "${FORCE_PROVISIONING}" -ne 1 ]] ; then
-    prompt_user "Please eject the installation media and restart the system (Reboot, poweroff, shell)" "^(reboot|poweroff|shell)$" "reboot" PROVISION_REBOOT_METHOD
+	prompt_user "Please eject the installation media and restart the system (Reboot, poweroff, shell)" "^(reboot|poweroff|shell)$" "reboot" PROVISION_REBOOT_METHOD
 fi
 
 cleanup_and_exit 0
