initrdscripts: Allow specifying a nilrt partition when provisioning
The PXI Platform Services group requested a way to install onto a DAQ
Imaging system where they have their own bootloader and disk
partitions. They wanted to specify the target partition for nilrt.
They do not need the nigrub and nirestore partitions.

The new option is named PROVISION_PART_NILRT_ID and can be specified
in an answers file. See the default answers file for documentation.

Signed-off-by: Jeff Pautler <jeffrey.pautler@ni.com>
Natinst-CAR-ID: 649716

diff --git a/recipes-core/initrdscripts/files/disk_config_x64 b/recipes-core/initrdscripts/files/disk_config_x64
--- a/recipes-core/initrdscripts/files/disk_config_x64
+++ b/recipes-core/initrdscripts/files/disk_config_x64
@@ -59,6 +59,25 @@ partition_format()
     esac
 }
 
+existing_nilrt_partition_format()
+{
+    local partition="$1" uuid="$2"
+
+    partition_check $partition
+    if [[ -n "$uuid" ]]; then
+        mkfs.ext4 -F -L nilrt -U $uuid $partition
+    else
+	mkfs.ext4 -F -L nilrt $partition
+    fi
+}
+
+partition_check()
+{
+    local partition="$1"
+
+    [[ -e "$partition" ]] || die "Invalid or unspecified partition!"
+}
+
 disk_format()
 {
    local disk="$1"
