initrdscripts: refactor disk_config_x64
Signed-off-by: Cristian Prigoana <cristian.prigoana@ni.com>

diff --git a/recipes-core/initrdscripts/files/disk_config_x64 b/recipes-core/initrdscripts/files/disk_config_x64
--- a/recipes-core/initrdscripts/files/disk_config_x64
+++ b/recipes-core/initrdscripts/files/disk_config_x64
@@ -1,62 +1,106 @@
 #!/bin/bash
 
-partition_format()
+die()
 {
-
-    mkfs.ext4 $MKFS_ARGS ${TARGET_DISK}4 -L $PART4_LABEL || die "Format failed!"
+    echo $1 && exit 1
 }
 
-disk_setup()
+install_default_error_handler()
 {
-    PARTED_ERROR=`parted -s $TARGET_DISK mklabel $PART_STYLE 2>&1` || die "$PARTED_ERROR"
-    PARTED_ERROR=`parted -s --align optimal $TARGET_DISK mkpart $PART1_NAME 1MB 16MB 2>&1` || die "$PARTED_ERROR"
-    PARTED_ERROR=`parted -s --align optimal $TARGET_DISK mkpart $PART2_NAME 16MB 200MB 2>&1` || die "$PARTED_ERROR"
-    PARTED_ERROR=`parted -s --align optimal $TARGET_DISK mkpart $PART3_NAME 200MB 216MB 2>&1` || die "$PARTED_ERROR"
-    PARTED_ERROR=`parted -s --align optimal $TARGET_DISK mkpart $PART4_NAME 216MB 100% 2>&1` || die "$PARTED_ERROR"
+    trap 'handle_err ${BASH_SOURCE} ${LINENO} ${FUNCNAME:-unknown} $? "$BASH_COMMAND"' ERR
+}
 
-    if [[ "$BOOT_STYLE" == "efi" ]]; then
+handle_err()
+{
+    TMP_EVAL=`eval echo $5`
+    die "$1:$2 (fn=$3): Unexpected status code $4 while running command: '$TMP_EVAL'"
+}
+
+if [[ -d /sys/firmware/efi ]];then
+    disk_partition()
+    {
+        local disk="$1"
+
+        parted -s "$disk" --align optimal   \
+            mklabel gpt                     \
+            mkpart nigrub         1MB  16MB \
+            mkpart nirestore     16MB 200MB \
+            mkpart niconfig     200MB 216MB \
+            mkpart nilrt        216MB  100%
+
         sgdisk --typecode=1:C12A7328-F81F-11D2-BA4B-00A0C93EC93B $TARGET_DISK
-    else
-        sfdisk -c $TARGET_DISK 1 EF
-    fi
-
-    MKFS_ERROR=`mkfs.vfat -n $PART1_LABEL ${TARGET_DISK}1 2>&1` || die "$MKFS_ERROR"
-    mkfs.ext4 $MKFS_ARGS ${TARGET_DISK}2 -L $PART2_LABEL || die "Format failed!"
-    mkfs.ext4 $MKFS_ARGS ${TARGET_DISK}3 -L $PART3_LABEL || die "Format failed!"
-    mkfs.ext4 $MKFS_ARGS ${TARGET_DISK}4 -L $PART4_LABEL || die "Format failed!"
-}
-
-PART1_LABEL=nigrub
-PART2_LABEL=nirestore
-PART3_LABEL=niconfig
-PART4_LABEL=nilrt
-
-# GPT partitions must assign a partition name whereas
-# MSDOS partitions must assign a partition type (e.g. primary)
-if [[ "$BOOT_STYLE" == "efi" ]]; then
-    PART_STYLE=gpt
-    PART1_NAME=$PART1_LABEL
-    PART2_NAME=$PART2_LABEL
-    PART3_NAME=$PART3_LABEL
-    PART4_NAME=$PART4_LABEL
+    }
 else
-    PART_STYLE=msdos
-    PART1_NAME=primary
-    PART2_NAME=primary
-    PART3_NAME=primary
-    PART4_NAME=primary
+    disk_partition()
+    {
+        local disk="$1"
+
+        parted -s "$disk" --align optimal   \
+            mklabel msdos                   \
+            mkpart primary       1MB  16MB  \
+            mkpart primary      16MB 200MB  \
+            mkpart primary     200MB 216MB  \
+            mkpart primary     216MB  100%
+
+        sfdisk -c "$disk" 1 EF
+    }
 fi
 
-TARGET_DISK=$2
-LABEL=$3
+partition_format()
+{
+    local disk="$1" label="$2"
 
-case $1 in
+    case "$label" in
+        nigrub)
+            mkfs.vfat -n nigrub "$disk"1
+            ;;
+        nirestore)
+            mkfs.ext4 -L nirestore "$disk"2
+            ;;
+        niconfig)
+            mkfs.ext4 -L niconfig "$disk"3
+            ;;
+        nilrt)
+            mkfs.ext4 -L nilrt "$disk"4
+            ;;
+        *)
+            die "Invalid or unspecified label!"
+    esac
+}
+
+disk_format()
+{
+   local disk="$1"
+
+   partition_format "$disk" nigrub
+   partition_format "$disk" nirestore
+   partition_format "$disk" niconfig
+   partition_format "$disk" nilrt
+}
+
+disk_check()
+{
+    local disk="$1"
+
+    [[ -b "$disk" ]] || die "Invalid or unspecified disk!"
+}
+
+install_default_error_handler
+
+cmd="$1"
+disk="$2"
+label="$3"
+
+case "$cmd" in
     "disk_setup")
-        disk_setup $TARGET_DISK
+        disk_check "$disk"
+        disk_partition "$disk"
+        disk_format "$disk"
         ;;
     "partition_format")
-        partition_format $TARGET_DISK $LABEL
+        disk_check "$disk"
+        partition_format "$disk" "$label"
         ;;
     *)
-        die "Unkown command $1!"
+        die "Unknown command $cmd!"
 esac
