nilrt-runmode-initramfs: Remove initramfs recipe and references
Remove the initramfs recipe since it is no longer needed by nilrt
boot sequence and unnecessarily complicates the boot logic.

This change will delete the enable_initramfs variable from the grub
environment during the installation of the runmode system.  If that
variable is not present, the system will not attempt to boot from
an initramfs, any implementations that require an initramfs in runmode
will not work with this change.

Signed-off-by: Bill Pittman <bill.pittman@ni.com>
Natinst-AzDO-ID: 1868559

diff --git a/recipes-ni/ni-utils/files/nisetbootmode b/recipes-ni/ni-utils/files/nisetbootmode
--- a/recipes-ni/ni-utils/files/nisetbootmode
+++ b/recipes-ni/ni-utils/files/nisetbootmode
@@ -35,11 +35,7 @@ else
 fi
 
 # Verify all the necessary utilities exist
-if [ "$NI_GRUB_ENABLE_BOOTFLAGS_DIR" -ge 1 ]; then
-	[ -f "$BOOTFLAGS_DIR/safemode" -o -f "$BOOTFLAGS_DIR/runtime" ] || fail "$0 error: Unable to find $BOOTFLAGS_DIR/safemode nor $BOOTFLAGS_DIR/runtime";
-else
-	[ -f "$BOOT_CONFIG_LOCATION" ] || fail "$0 error: Unable to find $BOOT_CONFIG_LOCATION";
-fi
+[ -f "$BOOT_CONFIG_LOCATION" ] || fail "$0 error: Unable to find $BOOT_CONFIG_LOCATION";
 
 case "$1" in
   start)
