nilrtdiskcrypt_open and nilrtdiskcrypt_format: Print mapped devices
Print path to mapped luks device (/dev/mapper/nilrtdiskcrypt_<whatever>)
after successful open. Enables users to write a file system and mount
it after provisioning a new disk or opening a existing disk.

Signed-off-by: Haris Okanovic <haris.okanovic@ni.com>
Natinst-Rally-ID: F12416
Natinst-ReviewBoard-ID: 204022

diff --git a/recipes-ni/nilrtdiskcrypt/files/nilrtdiskcrypt_format b/recipes-ni/nilrtdiskcrypt/files/nilrtdiskcrypt_format
--- a/recipes-ni/nilrtdiskcrypt/files/nilrtdiskcrypt_format
+++ b/recipes-ni/nilrtdiskcrypt/files/nilrtdiskcrypt_format
@@ -9,7 +9,8 @@ ERROR: $message
 
 Usage: $0 [ -u unsealedKeySlotNumber ...] [ -s sealedKeySlotNumber ...] [ -d devNode ... ]
  Generates and seals a new key in speicfied TPM key slots, then formats
- and opens specified partitions as luks using new key.
+ and opens specified partitions as luks using new key. Prints paths to
+ mapped device nodes.
 ENDHELP
     exit 1
 }
@@ -68,9 +69,15 @@ done
 status "Open devices"
 for devNode in $devNodes; do
     status "luksOpen devNode=$devNode"
+    mapperPath="`get_mapper_path "$devNode"`"
+    [ ! -e "$mapperPath" ] || error "devNode=$devNode already open at mapperPath=$mapperPath"
     cryptsetup \
         --key-file "$WORK_DIR/key" \
         luksOpen "$devNode" "nidiskcrypt_""`basename "$devNode"`"
+    [ -e "$mapperPath" ] || error "luksOpen failed to create mapperPath=$mapperPath"
+
+    # print mapped device path
+    echo "$mapperPath"
 done
 
 status "Store unsealed keys"
diff --git a/recipes-ni/nilrtdiskcrypt/files/nilrtdiskcrypt_open b/recipes-ni/nilrtdiskcrypt/files/nilrtdiskcrypt_open
--- a/recipes-ni/nilrtdiskcrypt/files/nilrtdiskcrypt_open
+++ b/recipes-ni/nilrtdiskcrypt/files/nilrtdiskcrypt_open
@@ -9,7 +9,7 @@ ERROR: $message
 
 Usage: $0 -k keySlotNumber [ -d devNode ... ]
  Unseals a key from specified key slot and opens specified devices
- with it.
+ with it. Prints paths to mapped device nodes.
 ENDHELP
     exit 1
 }
@@ -46,9 +46,15 @@ read_and_unseal_disk_key "$ksHandle"
 status "Open devices"
 for devNode in $devNodes; do
     status "luksOpen devNode=$devNode"
+    mapperPath="`get_mapper_path "$devNode"`"
+    [ ! -e "$mapperPath" ] || error "devNode=$devNode already open at mapperPath=$mapperPath"
     cryptsetup \
         --key-file "$WORK_DIR/key" \
         luksOpen "$devNode" "nidiskcrypt_""`basename "$devNode"`"
+    [ -e "$mapperPath" ] || error "luksOpen failed to create mapperPath=$mapperPath"
+
+    # print mapped device path
+    echo "$mapperPath"
 done
 
 status "Remove key"
